### ISSUE TITLE
Supporting HC-05?

### ISSUE THREAD

**Issue by renno-bih** [alexmos/sbgc-api-examples#3]
Hi, 
I can see that support for HC-10 is just added. Does it really works? It is great to see much cheaper BT module :)
What about supporting HC-05 that is also very popular cheap BT module?

RN-42 is based on the same BT chip that HC-05 uses, only different firmware is used.
HC-05 can also work in master mode. Are thee any obstacles in supporting this BT module?

**Comment by alexmos** [comment]
Hello,

Yes, I tested HM-10 it works. Regaring supporting other modules, I am not planning to add it, because it's just an example, and the bluetooth 
support is not an essential part of it. Somebody can modify program for their needs.  I think that HC-05 uses very similar set of AT-commands 
and it will take minimal effort.

Regards,
Aleksey Moskalenko
http://www.simplebgc.com
http://www.basecamelectronics.com

05.03.2017 13:46, renno-bih пишет:

**Comment by renno-bih** [comment]
Thank you @alexmos  

it is good to know that HM-10 works. I'll try with HM-10 :)
HC-05 will require additional pin. Pin34 should be pulled HIGH if you want to enter AT mode. So it complicates design.
As price is very similar I'll stick to HM-10 :)

**Comment by alexmos** [comment]
I think HC-05 does not require additional pins - I configured it by AT commands via Rx,Tx only. It is in AT mode when not linked by radio.
But note that HM-10 is BLE (4.0), HC-05 is EDR (2.1), they are not compatible each other. Also, BLE has a limited bandwidth.

Regards,
Aleksey Moskalenko
http://www.simplebgc.com
http://www.basecamelectronics.com

06.03.2017 11:24, renno-bih пишет:

**Comment by renno-bih** [comment]
I've just unpacked brand new HC-05, connected it to UART adapter but it doesn't respond to commands no matter what speed I choose. Red led blinks rapidly. But as there is button on module it is really easy to press it. But when module is in enclosure it can be tricky.
There are two ways for entering AT mode that I just checked:

1. Hold button and apply power - AT mode will work on 38400 speed.
2. Apply power to module and press button - AT mode will work on 9600 speed.

As I'm using ATMega328P and few additional components I was afraid that there won't be digital pins left for connecting PIN32 of HC05. But there is one digital pin left that I can connect to HC05 :)

I'll try to add HC05 and share it if I succeed :)

**Comment by alexmos** [comment]
Hi,

I didn't remember such tricks, I remember that I just configured is somehow.  So, you will need additional PIN to enter AT mode and start 
connection as a master. But I see it can auto-connect, so may be you need to configure it only once.


Regards,
Aleksey Moskalenko
http://www.simplebgc.com
http://www.basecamelectronics.com

06.03.2017 22:53, renno-bih пишет:

**Comment by binloan** [comment]
@renno-bih There are several different HC-05 modules on the market. Some don't have the "key" pin, but have a button to enable this mode. If you don't want to rebuy another HC-05 module I would recommend you desoldering the button, connect it permanently (as if you would hold the button). Then connect the pin to your microcontroller and set it to HIGH. The HC-05 should then go in AT mode. (AT mode on HC-05 is always 9600 baud)

However I would always prefer the HM-10 since it's Bluetooth Low Energy which is much more energy efficient and is supported by iOS devices aswell.

**Comment by renno-bih** [comment]
I successfully tested HC-05  #4 and works great.
What I had to do is to pull KEY pin to 3.3V. There is no need to set it to HIGH using microcontroller. With this approach you will save one digital pin :)

**Comment by alexmos** [comment]
Hi, renno.
Nice work, I merged without problems "as is". Thanks for your contribution!
I have burned my HC-05 long time ago, so can't test it now, but hope later I will order new one and test.

Regards,
Aleksey Moskalenko
http://www.simplebgc.com
http://www.basecamelectronics.com

15.03.2017 1:00, renno-bih пишет:
